export const logIn = {
  POST_LOGIN_INITIATE: "POST_LOGIN_INITIATE",
  POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
  POST_LOGIN_FAILURE: "POST_LOGIN_FAILURE",
};

export const forgetPassword = {
  POST_FORGET_PASSWORD_INITIATE: "POST_FORGET_PASSWORD_INITIATE",
  POST_FORGET_PASSWORD_SUCCESS: "POST_FORGET_PASSWORD_SUCCESS",
  POST_FORGET_PASSWORD_FAILURE: "POST_FORGET_PASSWORD_FAILURE",
};

export const changePassword = {
  CHANGE_PASSWORD_INITIATE: "CHANGE_PASSWORD_INITIATE",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
};

export const logOut = {
  LOGOUT_INITIATE: "LOGOUT_INITIATE",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const types = {
  GET_USERS_COUNT_INITIATE: "GET_USERS_COUNT_INITIATE",
  GET_USERS_COUNT_SUCCESS: "GET_USERS_COUNT_SUCCESS",
  GET_USERS_COUNT_FAILURE: "GET_USERS_COUNT_FAILURE",
};
export const blockUnblock = {
  PUT_BLK_UNBLK_INITIATE: "PUT_BLK_UNBLK_INITIATE",
  PUT_BLK_UNBLK_SUCCESS: "PUT_BLK_UNBLK_SUCCESS",
  PUT_BLK_UNBLK_FAILURE: "PUT_BLK_UNBLK_FAILURE",
};
export const uDetail = {
  GET_DETAIL_INITIATE: "GET_DETAIL_INITIATE",
  GET_DETAIL_SUCCESS: "GET_DETAIL_SUCCESS",
  GET_DETAIL_FAILURE: "GET_DETAIL_FAILURE",
};
export const user_update = {
  PUT_UPDATE_INITIATE: "PUT_UPDATE_INITIATE",
  PUT_UPDATE_SUCCESS: "PUT_UPDATE_SUCCESS",
  PUT_UPDATE_FAILURE: "PUT_UPDATE_FAILURE",
};
export const uList = {
  POST_USER_LIST_INITIATE: "POST_USER_LIST_INITIATE",
  POST_USER_LIST_SUCCESS: "POST_USER_LIST_SUCCESS",
  POST_USER_LIST_FAILURE: "POST_USER_LIST_FAILURE",
};
export const paymentList = {
  POST_PLIST_INITIATE: "POST_PLIST_INITIATE",
  POST_PLIST_SUCCESS: "POST_PLIST_SUCCESS",
  POST_PLIST_FAILURE: "POST_PLIST_FAILURE",
};
export const notificationDel = {
  DELETE_NOTIFICATION_INITIATE: "DELETE_NOTIFICATION_INITIATE",
  DELETE_NOTIFICATION_SUCCESS: "DELETE_NOTIFICATION_SUCCESS",
  DELETE_NOTIFICATION_FAILURE: "DELETE_NOTIFICATION_FAILURE",
};
