const appconstant = {
  changepassword: 'Change Password',
  Oldpassword: 'Old Password',
  NewPassword: 'New Password',
  ConfirmNewPassword: 'Confirm New Password',
  contactus: 'Contact us',
  home: 'Dashboard',
  EmailAddress: 'Email Address',
  eventManagement: 'Event Management',
  UserManagement: 'User Management',
  view: 'View',
  edit: 'Edit',
  block: 'Block',
  update: 'Update',
  export: 'Export',
  add: 'Add',
  Password: 'Password',
  ConfrmPassword: 'Confrm Password',
  email: 'Email',
  contactNo: 'Contact No',
  gender: 'Gender',
  age: 'Age',
  name: 'Name',
  organizerDetails: 'Organizer Details',
  eventOrganizermanagement: 'Event Organizer management',
  delete: 'Delete ',
  purposeManagement: 'Purpose Management',
  eventDetails: 'Event Details',
  organizer: 'Organizer',
  eventDate: 'Event Date',
  eventPlace: 'Event Place',
  ticketsSold: 'Tickets Sold',
  purposeDetails: 'Purpose Details',
  monetaryAward: 'Monetary Award',
  editEventDetail: 'Edit Event Detail',
  teamMembers: 'Team Members',
  teamMemberDetails: 'Team Member Details',
  editUserDetails: 'Edit User Details',
  editDetails: 'Edit Details',
  editPurposeDetail: 'Edit Purpose Detail',
  purposeOfTheEvent: 'Purpose Of The Event',
  from: 'From',
  userDetails: 'user Details',
  teamMembersEditDetails: 'Team Members Edit Details',
  productManagement: 'Product Management',
  activate: 'Activate',
  duplicate: 'Duplicate',
  productName: 'Product Name',
  price: 'Price (£A)',
  productDetails: 'Product Details',
  editProductDetails: 'Edit Product Details',
  productImage: 'Product Image',
  orderManagement: 'Order Management',
  orderDetails: 'Order Details',
  filmPrice: 'Film Price (£A)',
  customerName: 'Customer Name',
  orderPice: 'Order Price (£A)',
  roomSize: 'Room Size (mm*mm)',
  partition: 'partition',
  pannel: 'Pannel Size (mm)',
  frame: 'Frame Type',
  frameVariant: 'Frame Variant',
  doorChannel: 'Door Channel',
  doorGlass: 'Door Glass',
  doorCategoryHinges: 'Door Category/Hinges',
  handle: 'Handle Type',
  film: 'Film',
  length: 'Linear Length (mm) ',
  breadth: 'Linear Width (mm)',
  defaultRoomSize: ' Room Size',
  buttonedit: 'Edit',
  editDefaultRoomSize: 'Edit  Room Size',
  partition: 'Partition (mm)',
  permmPrice: 'Per mm Price',
  editPartition: 'Edit Partition',
  panels: 'Panels ',
  addnewpanel: 'Add New Panel',
  addNewPanel: 'Add New Panel',
  panelSize: 'Panel Size (mm)',
  panelPrice: 'Panel Price (£A)',
  buttonAdd: 'Add',
  pannelDetails: 'Panel Details',
  editPanelDetails: 'Edit Panel Details',
  frameType: 'Frame Type',
  frameVariant: 'Frame Variant',
  MarkAsDefault: 'Mark As Default',
  frameAndColor: 'Frame And Color',
  handleSides: 'handle Sides',
  handles: 'Handles',
  handleVariants: 'Handle Variants',
  editSingleMetalGlazed: 'Edit Single Metal Glazed',
  framePrice: 'Frame Price Per mm (£A)',
  filmPrice: 'Film Price (£A)',
  filmPriceIncludedToBasePric: 'Film Price Included To Base Pric',
  film: 'Add Film ',
  editFilmDetails: 'Edit Film Details',
  doorGlass: 'Door Glass ',
  editDoorGlass: 'Edit Door Glass ',
  glassSize: 'Glass Size (mm)',
  channelSize: 'Channel Size (mm)',
  doorChannel: 'Door Channel',
  doorType: 'Door Type',
  disable: 'Disable',
  editSingleDoor: 'Edit Single Door',
  doorType: 'Door Type',
  size: 'Size (mm) ',
  editDoubleDoor: 'Edit Double Door',
  doorCategoryAndHinges: 'Door Category And Hinges',
  doorCategory: 'Door Category',
  ConfigurationManagement: 'Configuration Management',
  orderID: 'Order ID',
  orderDateTime: 'Order Date/Time',
  handleVariant: 'Handle Variant',
  download: 'Download',
  productImage: 'Product Image',
  filmName: 'Film Name',
  filmImage: 'Film Image',
  addnewfilm: 'Add New Film',
  editframetype: 'Edit Frame Type',
  deactivate: 'Deactivate ',
  doorGlassm: 'Door Glass(mm)',
  variantsType: '	Variants Type',
  editHandles: 'Edit Handles',



  userName: 'User Name',
  deviceID: 'Device ID',
  emailAddress: 'Email Address',
  phoneNumber: 'Phone Number',
  totalMatchPlayed: 'Total Match Played',
  totalWins: 'Total Wins',
  totalWin: 'Total Win %',
  numberOfDrayagespecialist: 'Number Of Drayagespecialist Voice Games Played',
  numberOfDrayagespecialistTextmessageGamesPlayed: 'Number Of Drayagespecialist Text Message Games Played',
  badBehaviour: 'Bad Behaviour ',
  acountType: 'Acount Type',
  lastSeen: 'Last Seen',
  reports: 'Reports',
  reportsReceived: 'Reports Received',
  gemsCount: 'Gems Count',
  coinCount: 'Coin Count',
  userDetails: 'User Details',
  messages: 'Messages',





  john: 'john',
  emailname: 'john@yopmail.com',

  address: 'Address',
  mohali: 'Mohali',
  blogManagement: 'Blog Management',
  blogDetails: 'Blog Details',
  title: 'Title',
  loremIpsum: 'Lorem Ipsum',
  description: 'Description',
  lorem: 'Lorem Ipsum is simply dummy text',
  editblogdetails: 'Edit Blog Details',
  addblog: 'Add Blog',
  add: 'Add',
  clientManagement: 'Client Management',
  aboutus: 'About Us',
  addaboutus: 'Add About Us',
  generatepass: 'Generate Password',
  employeeManagement: 'Employee Management',
  lastname: 'Last Name',
  dee: 'Dee',
  firstname: 'First Name',
  editEmployeeDetails: 'Edit Employee Details',
  employeedetails: 'Employee Details',
  addemployee: 'Add Employee',
  clientName: 'Client Name',
  designation: 'Designation',
  manager: 'Manager',
  details: 'Details',
  clientDetails: 'Client Details',
  editclientDetails: 'Edit Client Details',
  addclient: 'Add Client',
  keywords: 'Keywords',
  editaboutus: 'Edit About Us',
  seoManagement: 'Seo Management',
  scoDetails: 'Seo Details',
  screeing: 'Screen',
  Home: 'Home',
  blog: 'Blog',
  editscoDetails: 'Edit Seo Details',
  metatitle: 'Meta Title',
  metadescription: ' Meta Description',
  metitle: 'How We Can Help',
  dis: 'We provide you with trained virtual Drayage Specialists who help businesses cover multiple administrative and operational tasks ',

  blogtitle: 'Everything you need',
  bligdis: 'Drayage is the transportation of products in a container hauled by truck in the shipping and logistics industry.',




  userManagement: 'User Management',
  respass: 'Reset Password',
  userdetails: 'User Details',
  usnam: 'Abc@123',
  usemail: 'Abc@123gmail.com',
  number: '+91 984115111',
  totalGamesPlayed: 'Total Games Played',
  played: '5',
  gamesLose: 'Games Lose',
  lose: '2',
  gameswin: 'Games Win',
  win: '3',
  country: 'Country',
  ind: 'India',
  state: 'State',
  ab: 'Abc',
  streetAddress: 'Street Address',
  xyz: 'Xyz',
  city: 'City',
  moh: 'Mohali',
  postalCode: 'Postal Code',
  code: '176244',
  faceID: 'Face ID',
  enabel: 'Enable',
  userAvgRating: 'User Avg. Rating',
  star: '5 star',
  fingerprint: 'Finger Print',
  enabel: 'Enable',
  totalRealAmount: 'Total Real Amount',
  amount: '$200',
  coinCount: 'Coin Count',
  count: '200',
  edituserDetails: 'Edit User Details',
  username: 'Username',
  name: 'Full Name',
  gameManagement: 'Game Management',
  gametype: 'Game Type',
  random: 'Random',
  tournamenttype: 'Tournament Type',
  knockout: 'Knockout',
  firstPlayerName: 'First Player Name',
  user1: 'User1',
  secondPlayerName: 'Second Player Name',
  user2: 'User2',
  date: 'Date',
  july: '10-july-2022',
  starttime: 'Start Time',
  tim: '02:00 PM',
  endtime: 'End Time',
  timeend: '02:20 PM',
  gamechoice: 'Game Choice',
  mint: '15 minutes',
  amounttype: 'Amount Type',
  realmoney: 'Real money',
  buy: 'Buy-In Amount',
  amo: '$100',
  totalmoves: 'Total Moves',
  movi: '75 Moves',
  gamestatus: 'Game Status',
  complete: 'Complete',
  winnername: 'Winner Name',
  winneramount: 'Winner Amount',
  amount: '$90',
  moves: 'Moves',
  nf3: '1.Nf3 Nf6, 2.c4 c5, 3.g3 g6, 4.Bg2',
  gameDetails: 'Game Details',
  addtournament: 'Add Tournament',
  tournamentname: "Tournament Name",
  abc123: 'Abc',
  startdate: 'Tournament Start Date',
  totalnum: 'Total Number Of Players',
  eigh: '5',
  entryFee: 'Entry Fee ',
  fee: '$500',
  winner: 'Winner',
  xy: 'xyz@123',
  runnerUp: 'Runner Up',
  ab: 'Abc@123',
  amou: '$600',
  runnerUpAmount: "Runner Up Amount",
  runupam: '$300',
  editTournamentDetails: 'Edit Tournament Details',
  tournamentManagement: 'Tournament Management',
  tournamentDetails: 'Tournament Details',
  depositsManagement: 'Deposits Management',
  deposits: 'Deposits',
  withdraw: 'Withdraw',
  notifcationManagement: 'Notification Management',
  addNotification: 'Add Notification',
  titile: 'Title',
  description: 'Description',
  editNotification: 'Edit Notification',
  tournamentStartDate: 'Tournament Start Date',
  tournamentStartTime: 'Tournament Start Time',
  tournamentEndTime: 'Tournament End Time',
  timeForEachMatch: 'Time For Each Match',
  entryFees: 'Entry Fees',
  poolPrice: 'Pool Price',
  timeInterval: 'Time Interval',
  nextTournamentGenerateDate: 'Next Tournament Generate Date',
  nextTournamentGenerateTime: 'Next Tournament Generate Time',
  totalTournaments: 'Total Tournaments',
  withdrawManagement: 'Withdraw Management',
  totalMoves: 'Total Moves',
  move: '75 Moves',


















  // 


  //










  //
  buttonupate: 'Update'

}
export default appconstant